use_frameworks!

target 'MyCocoaPodLib_Example' do
  pod 'MyCocoaPodLib', :path => '../'

  target 'MyCocoaPodLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
